### PR TITLE
Added href to local links, fixed rafinograde external links

### PR DESCRIPTION
**Pull request by nathanwentworth**
Hello again!! It looks like I changed a lot but that was just my sublime text deleting trailing white space, whoops!! 
- I fixed a typo/error in `lexicon.tome` for Rafinograde where the iTunes/Github links were linking to nothing
- I also added href attributes to local links to allow opening in a new tab/right-clicking to get URL/middle-clicking/etc! I tested in Firefox 61 and Chromium 66 and everything seems to work fine.

### CODE REVIEW

**Comment by neauoire** [comment]
Could you fix the conflict, sorry I just pushed a tiny thing.

**Comment by neauoire** [comment]
lexicon.tome is now lexicon.ndtl

**Comment by nathanwentworth** [comment]
ah whoops, i forgot to update my fork so i'm *super* behind yours. will commit the fixed versions later!!

**Comment by nathanwentworth** [comment]
Fixed!

**Comment by neauoire** [comment]
Thanks for that : ) It'll make a lot of people happy!

**Pull request merged**
