### PR TITLE
Fix typo in firth.html s/potsfix/postfix

### PR DESCRIPTION
**Pull request by deejoe**
Small typo fix in firth.html potsfix -> postfix

### CODE REVIEW

**Comment by deejoe** [comment]
Downloaded a local clone as is my practice and dang if >600MB isn't a lot to d/l for a single two-character transposition typo fix lol.

**Comment by neauoire** [comment]
Ah yeah, it's a horrible HORRIBLE repo, it has years' worth of junk. I will make a big squash at some point :) You can use the github interface to suggest an edit like that next time :)

**Comment by neauoire** [comment]
You're modifying the generated file in your PR, can you make that edit in lexicon.ndtl under FIRTH?

**Comment by deejoe** [comment]
Closing in favor of #67

**Pull request closed without merging**
